### ISSUE TITLE
Failure when trying to download an area

### ISSUE THREAD

**Issue by mz-pdm** [tyrylu/feel-the-streets#3]
When I try to download Pasohlávky area, the download freezes soon and I get the following traceback:

```
Traceback (most recent call last):
  File "/home/pdm/feel-the-streets/app/server_interaction/http.py", line 67, in run
    for chunk in resp.iter_content(chunk_size):
  File "/usr/lib/python3/dist-packages/requests/models.py", line 751, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 564, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 490, in read
    self._init_decoder()
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 362, in _init_decoder
    content_encoding = self.headers.get("content-encoding", "").lower()
  File "/usr/lib/python3.8/_collections_abc.py", line 660, in get
    return self[key]
SystemError: <function HTTPHeaderDict.__getitem__ at 0x7fa41ca2f940> returned NULL without setting an error
```

**Comment by tyrylu** [comment]
Not much i can do about that one, according to the few results about that error, it's raised when a C extension breaks the Python's object protocol...
